# Generated by Django 2.2.3 on 2022-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de Categoria', max_length=100)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
